name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Run Laravel Tests
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        run: php artisan test

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker images
        run: |
          docker compose build
          docker tag containers-app-app ${{ secrets.DOCKERHUB_USERNAME }}/containers-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/containers-app:latest

      - name: Deploy Locally
        run: |
          git config --global --add safe.directory /var/www/containers-app
          cd /var/www/containers-app || exit 1
          git reset --hard
          git pull origin main
          docker compose pull
          docker compose up -d --remove-orphans

      - name: Send Email Notification after run
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Pipeline Status: ${{ job.status }}"
          to: your-email@example.com
          from: GitHub Actions <github-actions@example.com>
          content_type: text/html
          body: |
            Hello me,
            The pipeline for repository ${{ github.repository }} has finished.
            Status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
            Regards,
            GitHub Actions

      # - name : Send Email 

